<?php

/**
 * Template pemetaan Kategori → Bucket — YFD AI Taxonomy v1.3 (Agustus 2026).
 * Sub kategori dipakai internal untuk mapping; dashboard hanya tampilkan kategori.
 */
return [
    // Saving instruments
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Protection', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'dana darurat,emergency fund,top up emergency,topup emergency', 'reason' => 'Dana darurat = proteksi', 'sort_order' => 1],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'match_keywords' => 'dp rumah,dp properti,dp kpr,dp ruko,uang muka rumah,uang muka properti', 'reason' => 'DP rumah/properti selalu Future Building', 'sort_order' => 2],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'match_keywords' => 'dp mobil,dp motor,dp kendaraan,uang muka mobil,uang muka motor', 'reason' => 'DP kendaraan kebutuhan → Future Building (jenis Saving/Investment)', 'sort_order' => 3],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'dp mobil kedua,dp motor kedua,dp kendaraan kedua,dp mobil upgrade,dp motor upgrade,dp mobil lifestyle,dp motor lifestyle,uang muka mobil kedua,uang muka motor kedua', 'reason' => 'DP kendaraan lifestyle → Flexible + Social (jenis Pengeluaran)', 'sort_order' => 4],
    ['category' => 'Investasi & Tabungan', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'saham,reksadana,emas,obligasi,deposito,crypto,nabung,investasi', 'reason' => 'Investasi & tabungan', 'sort_order' => 5],
    ['category' => '*', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'reason' => 'Default saving', 'sort_order' => 6],

    // Kewajiban Pajak (jenis terpisah — di luar 4 bucket)
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Transfer (Excluded)', 'transaction_type' => 'tax', 'reason' => 'Kewajiban Pajak dikecualikan dari 4 bucket', 'sort_order' => 0],
    // Piutang + Hutang (§5 Likuiditas Sosial — di luar 4 bucket)
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Transfer (Excluded)', 'transaction_type' => 'receivable_out', 'reason' => 'Piutang Keluar dikecualikan dari 4 bucket', 'sort_order' => 0],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Transfer (Excluded)', 'transaction_type' => 'receivable_in', 'reason' => 'Piutang Masuk dikecualikan dari pendapatan & 4 bucket', 'sort_order' => 0],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Transfer (Excluded)', 'transaction_type' => 'payable_in', 'reason' => 'Utang Masuk dikecualikan dari pendapatan & 4 bucket', 'sort_order' => 0],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Transfer (Excluded)', 'transaction_type' => 'payable_out', 'reason' => 'Utang Keluar dikecualikan dari 4 bucket', 'sort_order' => 0],

    // Income
    ['category' => 'Gaji', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'gaji,salary,payroll', 'reason' => 'Pemasukan gaji', 'sort_order' => 10],
    ['category' => 'Bonus', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'bonus,thr,insentif', 'reason' => 'Bonus/THR', 'sort_order' => 11],
    ['category' => 'Freelance', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'freelance,honor,honorarium', 'reason' => 'Honor/freelance', 'sort_order' => 12],
    ['category' => 'Affiliate', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'affiliate,afiliasi,komisi,commission,referral', 'reason' => 'Komisi affiliate', 'sort_order' => 13],
    ['category' => 'Dividen', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'dividen,dividend', 'reason' => 'Dividen cair', 'sort_order' => 14],
    ['category' => 'Bunga Investasi', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'bunga,interest', 'reason' => 'Bunga investasi', 'sort_order' => 15],
    ['category' => 'Cashback', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'cashback', 'reason' => 'Cashback', 'sort_order' => 16],
    ['category' => 'Refund', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'refund,pengembalian', 'reason' => 'Refund', 'sort_order' => 17],
    ['category' => 'Penjualan', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'hasil jualan,omzet', 'reason' => 'Hasil penjualan', 'sort_order' => 18],
    ['category' => 'Sewa Masuk', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'terima sewa,hasil sewa', 'reason' => 'Pendapatan sewa', 'sort_order' => 19],
    ['category' => 'Transfer Masuk', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'transfer masuk,kiriman', 'reason' => 'Transfer masuk', 'sort_order' => 20],

    // Context overrides
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'match_keywords' => 'konsumsi meeting,take konten,konten bisnis,meeting bisnis,rapat bisnis,meeting kerja,meeting kerjaan,rapat kerja,meeting klien,meeting untuk kerja,bisnis yfd,modal usaha,website bisnis,software bisnis,marketing bisnis,chatgpt,claude.ai,notion,canva pro,figma,networking bisnis,ketemu client,ketemu klien,ketemu bisnis,urusan bisnis,client bisnis,klien bisnis,starbucks meeting,ngopi meeting,kopi meeting,makan meeting', 'reason' => 'Biaya bisnis / konsumsi meeting kerja → Future Building', 'sort_order' => 20],
    // Gym/olahraga berbayar SELALU Flexible (taxonomy §2.9 / §2.18) — sebelum keyword coaching/les self-dev.
    ['category' => 'Lifestyle & Hiburan', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'sumber penghasilan,alat kerja langsung,saya personal trainer,aku personal trainer,saya atlet,aku atlet,atlet profesional,instruktur kebugaran,instruktur fitness', 'reason' => 'Gym/olahraga sebagai alat kerja fisik (PT/atlet) → Future Building', 'sort_order' => 204],
    ['category' => 'Lifestyle & Hiburan', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'gym,yoga,pilates,crossfit,personal trainer,coaching tenis,coaching padel,les renang,kelas pilates,kelas yoga,tenis,renang,padel,olahraga', 'reason' => 'Gym/olahraga berbayar selalu Flexible + Social', 'sort_order' => 205],
    ['category' => 'Pendidikan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'spp,ukt,uang sekolah,buku pelajaran,uang kuliah', 'reason' => 'Pendidikan wajib (prioritas sebelum self-dev)', 'sort_order' => 21],
    ['category' => 'Pendidikan', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'match_keywords' => 'seminar,workshop,kursus,sertifikasi,conference,pengembangan diri,coaching karier,coaching leadership,mentoring,les piano,les musik,les bahasa,public speaking,piano,iuran organisasi,keanggotaan profesi,iuran idi,bayar idi,asosiasi profesi,buku pengembangan,psychology of money,psychologi of money,buku finansial,buku financial', 'reason' => 'Pengembangan diri / iuran organisasi selalu Future Building (bukan olahraga)', 'sort_order' => 22],
    ['category' => 'Bisnis & Karir', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'meeting kerja,meeting kerjaan,rapat kerja,meeting klien,konsumsi meeting,ngopi meeting,meeting untuk kerja,starbucks meeting,kopi meeting', 'reason' => 'Konsumsi meeting kerja → Future Building (ekspektasi klien)', 'sort_order' => 23],
    ['category' => 'Lifestyle & Hiburan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'hp utama rusak,hp rusak,handphone rusak,ganti hp,hp pecah', 'reason' => 'HP utama rusak', 'sort_order' => 24],
    ['category' => 'Kesehatan & Kebersihan Diri', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'fisioterapi,rehab,rehabilitasi,resep dokter,hydrotherapy', 'reason' => 'Fisioterapi/rehab medis (resep) → Essential Living', 'sort_order' => 241],
    ['category' => 'Bisnis & Karir', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'modal usaha,marketing bisnis,iklan bisnis,website bisnis,website usaha,domain,hosting,laptop kerja,tools kerja', 'reason' => 'Bisnis & karir', 'sort_order' => 25],
    ['category' => 'Bisnis & Karir', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'reason' => 'Default bisnis & karir', 'sort_order' => 26],

    // Cicilan overrides (produktif / investasi sebelum default konsumtif)
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'cicilan modal,modal usaha,kpr investasi,kpr disewakan,kpr dikoskan,properti investasi,cicilan produktif', 'reason' => 'Cicilan produktif / KPR investasi', 'sort_order' => 27],
    ['category' => 'Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pbb investasi,pbb disewakan,pbb dikoskan,properti disewakan,properti dikoskan', 'reason' => 'PBB properti investasi → Future Building', 'sort_order' => 271],
    ['category' => 'Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'gaji art,bayar art,babysitter,baby sitter,pembantu,pengasuh,sopir pribadi,driver pribadi,gaji driver,menunjang kerja,agar bisa praktik', 'reason' => 'ART/driver/babysitter menunjang kerja → Essential Living', 'sort_order' => 272],
    ['category' => 'Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'kenyamanan,nyaman tambahan,driver pribadi lifestyle', 'reason' => 'ART/driver/babysitter kenyamanan → Flexible + Social', 'sort_order' => 273],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'tumbler rusak,ganti tumbler,tumbler ganti,ganti yang rusak,kulkas rusak,perabot rusak,termos rusak', 'reason' => 'Tumbler/perabot ganti rusak → Essential Living (bukan Protection)', 'sort_order' => 19],
    ['category' => 'Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'tumbler rusak,ganti tumbler,tumbler ganti,kulkas rusak,perabot rusak,belum memadai', 'reason' => 'Peralatan rumah tangga ganti rusak → Essential Living', 'sort_order' => 274],
    ['category' => 'Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'tumbler,termos,kulkas,rice cooker,mesin cuci,gorden,sprei,piring,perabot,koleksi,tren,upgrade', 'reason' => 'Peralatan rumah tangga koleksi/tren → Flexible + Social', 'sort_order' => 275],
    ['category' => 'Transportasi', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pesawat meeting,tiket meeting,training kerja,urusan bisnis,meeting klien,meeting kerja,meeting kerjaan,rapat kerja,perjalanan dinas,networking bisnis,networking,ketemu client,ketemu klien,ketemu bisnis,meeting client,meeting bisnis,klien bisnis,client bisnis,keperluan bisnis,perjalanan bisnis,kerja training,untuk bisnis,tujuan bisnis,ke bisnis,buat bisnis,keperluan usaha,ke klien,ke client,ke meeting,ke rapat,rapat klien,rapat client,ketemu calon klien,pitch client,pitch klien,investor meeting,dinas luar,acara bisnis,event bisnis', 'reason' => 'Transportasi bisnis/kerja (lokal & jarak jauh) → Future Building', 'sort_order' => 28],
    ['category' => 'Transportasi', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'grab ke gym,ojek ke gym,ke gym,ke fitness,dari kos ke gym,ke cafe,nongkrong,healing,mall,wisata,arisan,will fitness,hangout', 'reason' => 'Transportasi leisure/sosial (Grab ke gym dll)', 'sort_order' => 29],
    ['category' => 'Transportasi', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'subscription grab,grab subscription,langganan grab,grab unlimited,paket hemat grab,subscription gojek,langganan gojek', 'reason' => 'Langganan ojek (Grab/Gojek) → Flexible + Social', 'sort_order' => 291],

    // Essential Living
    ['category' => 'Makanan & Minuman', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'makan,nasi,sarapan,bahan makanan,air minum,galon', 'reason' => 'Kebutuhan makan harian', 'sort_order' => 30],
    ['category' => 'Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'kos,kontrakan,kpr,listrik,pln,pdam,gas,ipl,wifi rumah,detergen,cairan pel,pbb,pajak bumi,pajak bangunan,gaji art,babysitter,pembantu', 'reason' => 'Tempat tinggal, utilitas, PBB tinggal & ART default Need', 'sort_order' => 31],
    ['category' => 'Transportasi', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'ojek,grab,gojek,bensin,tol,parkir,krl,angkot,kantor,klinik,apotek,sekolah', 'reason' => 'Transportasi rutin/esensial', 'sort_order' => 32],
    ['category' => 'Komunikasi', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pulsa,kuota,paket data,biaya admin,biaya transfer,admin bank,tarik tunai', 'reason' => 'Komunikasi & admin bank', 'sort_order' => 33],
    ['category' => 'Kesehatan & Kebersihan Diri', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'dokter,obat,apotek,lab,laboratorium,medical,vitamin,minoxidil,sabun,shampo,pasta gigi,odol,softex,pembalut,deodoran,deodorant,handbody,hand body,body lotion,lotion,sikat gigi,cotton bud,hand sanitizer,nivea,vaseline,masker,laundry,cuci baju,dry clean,dryclean,fisioterapi,rehab', 'reason' => 'Medis & kebersihan dasar (laundry = Essential; skincare/makeup = Flexible)', 'sort_order' => 34],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'stnk,pkb,samsat,pajak kendaraan,pajak mobil,pajak motor', 'reason' => 'Pajak kendaraan kebutuhan kerja', 'sort_order' => 351],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'denda,tilang,sanksi keterlambatan,denda keterlambatan,denda cicilan', 'reason' => 'Denda & sanksi non-pajak → Essential Living', 'sort_order' => 352],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pinjol,pinjaman online,pinjaman tunai,kebutuhan mendesak,darurat', 'reason' => 'Pinjol mendesak (Need) → Essential Living + Risk Alert', 'sort_order' => 353],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'pinjol,pinjaman online,pinjaman tunai,konsumsi non-esensial,non esensial', 'reason' => 'Pinjol konsumsi non-esensial (Wants) → Flexible + Social + Risk Alert', 'sort_order' => 354],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'cicilan,angsuran,paylater,kartu kredit,kpr rumah tinggal', 'reason' => 'Cicilan konsumtif / KPR tinggal / kewajiban', 'sort_order' => 36],
    ['category' => 'Pakaian & Aksesoris', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'seragam,sepatu kerja,tas kerja,tas sekolah,sepatu sekolah', 'reason' => 'Perlengkapan kerja/sekolah', 'sort_order' => 37],
    ['category' => 'Biaya Legal, Administrasi & Peristiwa Besar', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'notaris rumah tinggal,balik nama rumah,ajb rumah tinggal', 'reason' => 'Notaris/legal ikut aset tinggal', 'sort_order' => 341],
    ['category' => 'Biaya Legal, Administrasi & Peristiwa Besar', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'notaris,balik nama,ajb,biaya legal', 'reason' => 'Notaris/legal terkait aset (default Future Building)', 'sort_order' => 38],

    // Protection
    ['category' => 'Proteksi', 'sub_category' => '-', 'bucket' => 'Protection', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'asuransi,premi asuransi,bpjs,asuransi kendaraan,asuransi mobil,all risk,tlo,asuransi properti', 'reason' => 'Premi asuransi/BPJS/kendaraan/aset', 'sort_order' => 40],

    // Flexible + Social
    ['category' => 'Makanan & Minuman', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'kopi,coffee,jajan,snack,boba,cafe,resto,kuliner,starbucks,healing', 'reason' => 'Jajan & kuliner', 'sort_order' => 50],
    ['category' => 'Transportasi', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'taksi bandara,sewa kendaraan wisata,liburan,tiket pesawat', 'reason' => 'Transportasi non-rutin / liburan', 'sort_order' => 51],
    ['category' => 'Lifestyle & Hiburan', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'netflix,spotify,gaming,bioskop,konser,hobi,gym,yoga,pilates,crossfit,gadget', 'reason' => 'Lifestyle & hiburan', 'sort_order' => 52],
    ['category' => 'Traveling', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'liburan,staycation,hotel,tiket pesawat,wisata', 'reason' => 'Traveling', 'sort_order' => 53],
    ['category' => 'Sosial & Keluarga', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'donasi,sedekah,persembahan,perpuluhan,zakat,qurban,kurban,bantu keluarga,bantu adik,bantu mama,transfer ortu,transfer ke mama,transfer ke ibu', 'reason' => 'Sosial & keluarga (termasuk Qurban)', 'sort_order' => 54],
    ['category' => 'Hadiah', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'hadiah,kado,parcel,souvenir,tip,tips', 'reason' => 'Hadiah', 'sort_order' => 55],
    ['category' => 'Pakaian & Aksesoris', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'fashion,baju,celana,sepatu,tas,aksesoris,kaos,sandal', 'reason' => 'Fashion & lifestyle', 'sort_order' => 56],
    ['category' => 'Lifestyle & Hiburan', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'reason' => 'Default lifestyle wants', 'sort_order' => 57],
    ['category' => 'Pakaian & Aksesoris', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'reason' => 'Default pakaian (grey area → Flexible kecuali Need kerja/sekolah)', 'sort_order' => 58],
    ['category' => 'Kesehatan & Kebersihan Diri', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'skincare,skin care,serum,toner,facial,make up,makeup,dandan,lipstik,lipstick,parfum,klinik kecantikan,cushion,maybelline,maybeline,sunscreen,pelembab,spa,potong rambut,salon rambut', 'reason' => 'Perawatan & kecantikan', 'sort_order' => 59],
    ['category' => 'Cicilan & Hutang', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'pajak kendaraan kedua,pajak mobil hobi,stnk kendaraan kedua', 'reason' => 'Pajak kendaraan lifestyle', 'sort_order' => 591],
    ['category' => 'Biaya Legal, Administrasi & Peristiwa Besar', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'mahar,pernikahan,resepsi,duka,pemakaman,tahlilan', 'reason' => 'Mahar/pernikahan/duka — Peristiwa Besar', 'sort_order' => 60],
    ['category' => 'Biaya Legal, Administrasi & Peristiwa Besar', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'reason' => 'Default legal/peristiwa besar', 'sort_order' => 61],
    ['category' => 'Lain-lain', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'reason' => 'Tidak terklasifikasi', 'sort_order' => 99],
];
