<?php

/**
 * Template pemetaan Kategori → Bucket — selaras taxonomy bot Telegram.
 * Sub kategori tidak dipakai (isi '-').
 */
return [
    // Saving instruments
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Protection', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'dana darurat,emergency fund,top up emergency,topup emergency', 'reason' => 'Dana darurat berfungsi sebagai proteksi', 'sort_order' => 1],
    ['category' => 'Saham', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'saham,avg down,beli saham', 'reason' => 'Investasi saham', 'sort_order' => 6],
    ['category' => 'Reksadana', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'reksadana,reksa dana,bibit', 'reason' => 'Investasi reksadana', 'sort_order' => 7],
    ['category' => 'Obligasi', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'obligasi,sbn', 'reason' => 'Investasi obligasi/SBN', 'sort_order' => 8],
    ['category' => 'Emas', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'nature' => 'Need', 'match_keywords' => 'emas,antam,beli emas', 'reason' => 'Investasi emas', 'sort_order' => 9],
    ['category' => '*', 'bucket' => 'Future Building', 'transaction_type' => 'saving', 'reason' => 'Semua nabung & investasi', 'sort_order' => 5],

    // Income
    ['category' => 'Gaji', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'gaji,salary,payroll,slip gaji', 'reason' => 'Pemasukan gaji', 'sort_order' => 10],
    ['category' => 'Bonus', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'bonus,thr,tunjangan hari raya,insentif', 'reason' => 'Bonus/THR/insentif', 'sort_order' => 11],
    ['category' => 'Freelance', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'freelance,honor,honorarium,fee project', 'reason' => 'Honor/freelance', 'sort_order' => 12],
    ['category' => 'Affiliate', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'affiliate,afiliasi,komisi,commission,referral,shopee affiliate,tiktok affiliate', 'reason' => 'Komisi affiliate marketplace', 'sort_order' => 13],
    ['category' => 'Dividen', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'dividen,dividend', 'reason' => 'Dividen yang dicairkan', 'sort_order' => 14],
    ['category' => 'Bunga Investasi', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'bunga investasi,bunga deposito,bunga tabungan,terima bunga,dapat bunga,interest,kupon obligasi,kupon sbn', 'reason' => 'Bunga/hasil investasi yang dicairkan', 'sort_order' => 15],
    ['category' => 'Cashback', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'cashback,cash back,rebate,redeem poin', 'reason' => 'Cashback/poin', 'sort_order' => 16],
    ['category' => 'Refund', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'refund,pengembalian dana,chargeback', 'reason' => 'Pengembalian dana', 'sort_order' => 17],
    ['category' => 'Penjualan', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'hasil jualan,hasil penjualan,omzet,jual barang', 'reason' => 'Hasil penjualan aset/barang', 'sort_order' => 18],
    ['category' => 'Sewa Masuk', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'terima sewa,hasil sewa,rental income,uang kos masuk', 'reason' => 'Pendapatan sewa', 'sort_order' => 19],
    ['category' => 'Transfer Masuk', 'sub_category' => '-', 'bucket' => 'Income', 'transaction_type' => 'income', 'nature' => 'Need', 'match_keywords' => 'transfer masuk,kiriman orang tua,kiriman keluarga', 'reason' => 'Transfer masuk / kiriman', 'sort_order' => 20],

    // Konteks tujuan — jenis tetap Pengeluaran, bucket mengikuti fungsi transaksi.
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'match_keywords' => 'les olahraga,coaching olahraga,kursus olahraga,personal trainer,fitness coach,kelas gym,kelas yoga,kelas pilates,les tenis,coaching tenis,pelatih tenis,kelas tenis,les renang,coaching renang,pelatih renang,kelas renang,les badminton,les bulu tangkis,coaching badminton,coaching basket,coaching sepak bola,coaching futsal,coaching golf', 'reason' => 'Les/coaching olahraga mendukung kesehatan', 'sort_order' => 20],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'match_keywords' => 'freelancer it,jasa freelancer it,web developer,website bisnis,website usaha,website proyek,software bisnis,software usaha,marketing bisnis,marketing usaha,modal usaha,proyek bisnis,project bisnis,proyek yfd', 'reason' => 'Biaya untuk membangun kapasitas bisnis', 'sort_order' => 21],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'match_keywords' => 'seminar,simposium,symposium,workshop,sertifikasi,pelatihan,kursus,course,conference,penelitian,buku pengembangan diri,pengembangan diri,self development,psychology of money,psychologi of money,les,coaching,mentoring,kelas piano,les piano,kursus piano,les musik,kelas musik,les vokal,les bahasa,kursus bahasa,public speaking,belajar piano,piano untuk belajar,latihan piano,alat musik untuk belajar,alat musik untuk profesi,profesi musik,untuk manggung,studio musik', 'reason' => 'Semua self-development selain olahraga', 'sort_order' => 22],
    ['category' => 'Alat Musik', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'reason' => 'Alat musik untuk belajar, pengembangan diri, atau profesi', 'sort_order' => 23],
    ['category' => 'Makan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'meeting kerja,rapat kerja,meeting klien,ngopi meeting,kopi meeting', 'reason' => 'Makan/minum untuk pertemuan kerja', 'sort_order' => 23],
    ['category' => 'Jajan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'meeting kerja,rapat kerja,meeting klien,ngopi meeting,kopi meeting', 'reason' => 'Kopi untuk pertemuan kerja', 'sort_order' => 24],
    ['category' => 'Elektronik', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'hp utama rusak,hp rusak,handphone rusak,ganti hp,hp pecah,layar pecah,hp mati', 'reason' => 'Penggantian HP utama rusak', 'sort_order' => 25],
    ['category' => 'Elektronik', 'sub_category' => '-', 'bucket' => 'Future Building', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'laptop kerja,laptop produktif,alat kerja,untuk kerja,modal kerja,laptop kantor,komputer kerja', 'reason' => 'Alat produktif / laptop kerja', 'sort_order' => 26],
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'fomo,healing,upgrade karena,ganti iphone tiap tahun', 'reason' => 'Belanja lifestyle / impulsif', 'sort_order' => 27],

    // Essential Living
    ['category' => '*', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'aqua,air minum,air mineral,air galon,galon air,beli galon,le minerale,pristine,cleo,crystalin,equil,kebutuhan hidup,kebutuhan sehari,kebutuhan harian,sembako,kebutuhan pokok', 'reason' => 'Air minum & kebutuhan hidup pokok', 'sort_order' => 28],
    ['category' => 'Makan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'makan,restoran,nasi,sarapan', 'reason' => 'Kebutuhan makan harian', 'sort_order' => 30],
    ['category' => 'Transport', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'ojek,grab,gojek,angkot,bensin,tol,parkir,servis,bengkel', 'reason' => 'Transportasi harian', 'sort_order' => 31],
    ['category' => 'Sewa/Tempat Tinggal', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'bayar sewa,sewa kos,kontrakan,kpr,cicilan rumah', 'reason' => 'Tempat tinggal', 'sort_order' => 32],
    ['category' => 'Pendidikan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'spp,uang sekolah,ukt,buku wajib,kebutuhan sekolah anak,les wajib,bimbel sekolah,kuliah', 'reason' => 'Pendidikan wajib', 'sort_order' => 33],
    ['category' => 'Komunikasi', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pulsa,kuota,paket data,wifi,indihome', 'reason' => 'Komunikasi/internet', 'sort_order' => 34],
    ['category' => 'Cicilan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'cicilan,angsuran,paylater,kredit motor', 'reason' => 'Cicilan/kredit', 'sort_order' => 35],
    ['category' => 'Listrik', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'listrik,pln,token', 'reason' => 'Utilitas tempat tinggal', 'sort_order' => 40],
    ['category' => 'Air', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pdam,tagihan air,rekening air', 'reason' => 'Utilitas tempat tinggal', 'sort_order' => 41],
    ['category' => 'Kesehatan', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'medical check up,obat,apotek,klinik,dokter,rumah sakit,laboratorium,vitamin', 'reason' => 'Kebutuhan kesehatan', 'sort_order' => 43],
    ['category' => 'Pajak', 'sub_category' => '-', 'bucket' => 'Essential Living', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'pajak,pph,ppn,pbb,stnk,samsat,administrasi bank', 'reason' => 'Pajak dan administrasi wajib', 'sort_order' => 44],

    // Protection
    ['category' => 'Asuransi', 'sub_category' => '-', 'bucket' => 'Protection', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'asuransi,premi,bpjs', 'reason' => 'Proteksi asuransi/BPJS', 'sort_order' => 42],

    // Flexible + Social
    ['category' => 'Alat Musik', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'reason' => 'Alat musik untuk hobi/hiburan pribadi', 'sort_order' => 49],
    ['category' => 'Jajan', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'kopi,coffee,jajan,snack,boba', 'reason' => 'Jajan & kopi', 'sort_order' => 50],
    ['category' => 'Elektronik', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'headset,earphone,earbuds,airpods,gadget,charger,powerbank,mouse,keyboard,speaker,monitor,tablet,laptop,hp,handphone,iphone,smartphone', 'reason' => 'Gadget & elektronik (bukan jajan)', 'sort_order' => 54],
    ['category' => 'Peralatan', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'tumbler,botol minum,peralatan,rumah tangga,pisau,panci,sendok', 'reason' => 'Peralatan rumah / lifestyle (bukan jajan)', 'sort_order' => 55],
    ['category' => 'Skincare', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'skincare,skin care,serum,moisturizer', 'reason' => 'Perawatan diri', 'sort_order' => 51],
    ['category' => 'Subscription', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Wants', 'match_keywords' => 'subscription,langganan,netflix,spotify,youtube premium', 'reason' => 'Langganan digital', 'sort_order' => 52],
    ['category' => 'Social', 'sub_category' => '-', 'bucket' => 'Flexible + Social', 'transaction_type' => 'expense', 'nature' => 'Need', 'match_keywords' => 'hadiah,amplop,sedekah,persembahan,ibadah,donasi,zakat', 'reason' => 'Sosial & donasi', 'sort_order' => 53],
];
