<?php

/**
 * 16 langkah diagnostik landing (sesuai mockup klien).
 * wizard_step 1 = profil (3 sub-soal), wizard_step 2-16 = soal ber-skor.
 */
return [
    'intro' => [
        'title' => 'Bantu kita Mengenal Profil kamu lebih dalam ya',
        'note' => 'Diisi sejujur-jujurnya ya, tujuan kami disini adalah bantu memberikan gambaran mengenai kondisi finansial kamu',
    ],

    'questions' => [
        [
            'wizard_step' => 1,
            'question_key' => 'q1',
            'section' => 'Profil',
            'text' => 'Kondisi Saat ini?',
            'note' => null,
            'is_scored' => false,
            'sort_order' => 1,
            'options' => [
                'pekerja' => 'Pekerja',
                'pemilik_usaha' => 'Pemilik Usaha',
                'tanggungan' => 'Masih sepenuhnya tanggungan orangtua',
                'kombinasi' => 'Kombinasi Pekerja dan Pengusaha',
            ],
        ],
        [
            'wizard_step' => 1,
            'question_key' => 'q2',
            'section' => 'Profil',
            'text' => 'Usia saat ini?',
            'note' => null,
            'is_scored' => false,
            'sort_order' => 2,
            'options' => [
                'lt_25' => '<25th',
                '25_34' => '25-34th',
                '35_44' => '35-44th',
                'gte_45' => '>=45th',
            ],
        ],
        [
            'wizard_step' => 1,
            'question_key' => 'q3',
            'section' => 'Profil',
            'text' => 'Jenis Kelamin',
            'note' => null,
            'is_scored' => false,
            'sort_order' => 3,
            'options' => [
                'laki' => 'Laki-laki',
                'perempuan' => 'Perempuan',
                'others' => 'Others',
            ],
        ],
        [
            'wizard_step' => 2,
            'question_key' => 'q4',
            'section' => 'Keamanan Finansial',
            'text' => 'Apakah Kamu memiliki Dana Darurat?',
            'note' => 'Dana Darurat = dana yang dipisahkan khusus hanya untuk kondisi darurat (ex: Jatuh sakit, Kecelakaan, HP rusak, dsb)',
            'is_scored' => true,
            'sort_order' => 4,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'lt_3x' => ['label' => 'Ada, <3x Pengeluaran perbulan', 'score' => 1],
                '3_5x' => ['label' => 'Ada, 3-5x Pengeluaran perbulan', 'score' => 2],
                'gt_6x' => ['label' => 'Ada, >=6x Pengeluaran perbulan', 'score' => 3],
            ],
        ],
        [
            'wizard_step' => 3,
            'question_key' => 'q5',
            'section' => 'Cash Flow',
            'text' => 'Seberapa Sering Pengeluaran > Pemasukan?',
            'note' => null,
            'is_scored' => true,
            'sort_order' => 5,
            'options' => [
                'almost_every' => ['label' => 'Hampir Setiap bulan', 'score' => 0],
                'often' => ['label' => 'Sering (>=6bulan/tahun)', 'score' => 1],
                'sometimes' => ['label' => 'Kadang-kadang (3-5 bulan/tahun)', 'score' => 2],
                'rare' => ['label' => 'Hampir tidak pernah (1-2bulan/tahun)', 'score' => 3],
                'never' => ['label' => 'Tidak Pernah', 'score' => 4],
            ],
        ],
        [
            'wizard_step' => 4,
            'question_key' => 'q6',
            'section' => 'Profil',
            'text' => 'Apakah kamu sudah punya Tanggungan?',
            'note' => 'Tanggungan = orang yang penghidupannya bergantung sama kamu',
            'is_scored' => true,
            'sort_order' => 6,
            'options' => [
                'none' => ['label' => 'Tidak Ada', 'score' => 2],
                'one' => ['label' => 'Ada, 1 orang', 'score' => 1],
                'many' => ['label' => '>1 orang', 'score' => 0],
            ],
        ],
        [
            'wizard_step' => 5,
            'question_key' => 'q7',
            'section' => 'Tabungan & Aset',
            'text' => 'Apakah sudah punya tabungan atau aset Produktif?',
            'note' => 'Aset produktif = aset yang menghasilkan penghasilan (ex: kos-kosan, sewa mobil dan sebagainya)',
            'is_scored' => true,
            'sort_order' => 7,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'savings' => ['label' => 'Tabungan saja', 'score' => 1],
                'productive' => ['label' => 'Aset produktif saja', 'score' => 2],
                'both' => ['label' => 'Tabungan + Aset', 'score' => 3],
            ],
        ],
        [
            'wizard_step' => 6,
            'question_key' => 'q8',
            'section' => 'Proteksi',
            'text' => 'Punya Proteksi/Asuransi Kesehatan?',
            'note' => 'Asuransi kesehatan ini berfungsi untuk menjaga kami dari resiko sakit',
            'is_scored' => true,
            'sort_order' => 8,
            'options' => [
                'none' => ['label' => 'Tidak punya', 'score' => 0],
                'bpjs' => ['label' => 'BPJS', 'score' => 1],
                'private' => ['label' => 'Asuransi Swasta/Kantor', 'score' => 2],
                'both' => ['label' => 'BPJS + Asuransi Swasta', 'score' => 3],
            ],
        ],
        [
            'wizard_step' => 7,
            'question_key' => 'q9',
            'section' => 'Pendapatan',
            'text' => 'Rata-rata pendapatan perbulan',
            'note' => 'Jawab sesuai dengan total pendapatan aktif dan pasif',
            'is_scored' => true,
            'sort_order' => 9,
            'options' => [
                'lt_2_5' => ['label' => '<=2.5jt', 'score' => 0],
                'lt_6_5' => ['label' => '<6.5jt', 'score' => 1],
                '6_5_12_9' => ['label' => '6.5-12.9jt', 'score' => 2],
                '13_24_9' => ['label' => '13-24.9jt', 'score' => 3],
                'gt_25' => ['label' => '>=25jt', 'score' => 4],
            ],
        ],
        [
            'wizard_step' => 8,
            'question_key' => 'q10',
            'section' => 'Cash Flow',
            'text' => 'Rata-rata Pengeluaran dibandingkan dengan Pemasukan perbulan',
            'note' => null,
            'is_scored' => true,
            'sort_order' => 10,
            'options' => [
                'greater' => ['label' => 'Pengeluaran > Pemasukan', 'score' => 0],
                'equal' => ['label' => 'Pengeluaran = Pemasukan', 'score' => 1],
                'less' => ['label' => 'Pengeluaran < Pemasukan', 'score' => 2],
            ],
        ],
        [
            'wizard_step' => 9,
            'question_key' => 'q11',
            'section' => 'Proteksi',
            'text' => 'Punya Asuransi Pelindung Pemasukan/Kondisi Kritis?',
            'note' => "Asuransi akan bisa di klaim apabila resiko berupa kondisi penyakit kritis terjadi\nTujuan utamanya -> menggantikan pemasukan yang tidak bisa didapatkan karena sakit kritis",
            'is_scored' => true,
            'sort_order' => 11,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'yes' => ['label' => 'Ada', 'score' => 2],
            ],
        ],
        [
            'wizard_step' => 10,
            'question_key' => 'q12',
            'section' => 'Proteksi',
            'text' => 'Punya Asuransi Jiwa?',
            'note' => 'Uang Pertanggungan asuransi ini akan bisa di klaim pada saat pemilik polis tutup usia (Contoh: Kebutuhan tahunan 60 jt, maka 5x UP artinya sekitar 300 jt)',
            'is_scored' => true,
            'sort_order' => 12,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'lt_5x' => ['label' => 'Ada, Uang Pertanggungan <5x pengeluaran tahunan', 'score' => 1],
                'gte_5x' => ['label' => 'Ada, Uang Pertanggungan >=5x pengeluaran tahunan', 'score' => 2],
            ],
        ],
        [
            'wizard_step' => 11,
            'question_key' => 'q13',
            'section' => 'Investasi',
            'text' => 'Punya Tabungan atau Investasi untuk Hari Tua/Pensiun?',
            'note' => 'Kalau belum punya jangan khawatir, belum banyak yang sudah punya ini kok',
            'is_scored' => true,
            'sort_order' => 13,
            'options' => [
                'none' => ['label' => 'Belum ada', 'score' => 0],
                'started' => ['label' => 'Baru mulai', 'score' => 1],
                'regular' => ['label' => 'Rutin ditabung', 'score' => 2],
                'planned' => ['label' => 'Sudah ada, dan terencana jelas', 'score' => 3],
            ],
        ],
        [
            'wizard_step' => 12,
            'question_key' => 'q14',
            'section' => 'Investasi',
            'text' => 'Punya Investasi High Risk?',
            'note' => 'ex: Crypto, Saham dalam negeri atau luar negeri, Reksadana saham',
            'is_scored' => true,
            'sort_order' => 14,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'unplanned' => ['label' => 'Ada, tapi tidak sepenuhnya paham', 'score' => 1],
                'planned' => ['label' => 'Ada, paham dan terencana', 'score' => 2],
            ],
        ],
        [
            'wizard_step' => 13,
            'question_key' => 'q15',
            'section' => 'Utang',
            'text' => 'Punya Hutang/cicilan konsumtif?',
            'note' => 'Hutang/cicilan konsumtif adalah hutang yang digunakan untuk keinginan dan bukan untuk usaha, termasuk hutang/cicilan keluarga',
            'is_scored' => true,
            'sort_order' => 15,
            'options' => [
                'gt_50' => ['label' => 'Ada, >50% dari pemasukkan perbulan', 'score' => 0],
                '25_50' => ['label' => 'Ada, 25-50% dari pemasukkan perbulan', 'score' => 1],
                'lt_25' => ['label' => 'Ada, <25% dari pemasukkan perbulan', 'score' => 2],
                'none' => ['label' => 'Tidak Ada', 'score' => 3],
            ],
        ],
        [
            'wizard_step' => 14,
            'question_key' => 'q16',
            'section' => 'Pendapatan',
            'text' => 'Punya Pemasukkan Pasif (Passive income)?',
            'note' => 'Passive income = pemasukkan yang didapatkan dari investasi tanpa perlu kita bekerja secara aktif (ex: bunga deposito, deviden saham, investasi di perusahaan)',
            'is_scored' => true,
            'sort_order' => 16,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'lt_10' => ['label' => 'Ada, <10% dari pengeluaran bulanan', 'score' => 1],
                '10_75' => ['label' => 'Ada, 10-75% dari pengeluaran bulanan', 'score' => 2],
                'gt_75' => ['label' => 'Ada, >75% dari pengeluaran bulanan', 'score' => 3],
            ],
        ],
        [
            'wizard_step' => 15,
            'question_key' => 'q17',
            'section' => 'Utang',
            'text' => 'Apakah kamu punya Hutang/Cicilan Produktif?',
            'note' => "Hutang/cicilan produktif adalah hutang yang digunakan untuk membiayai aset yang menghasilkan\nContoh: KPR untuk bangun kos-kosan, Kredit Mobil untuk taksi online",
            'is_scored' => true,
            'sort_order' => 17,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'lt_30' => ['label' => 'Ada, <30% dari pendapatan bulanan', 'score' => 1],
                'gt_30' => ['label' => 'ada, >30% dari pendapatan bulanan tapi tetap menghasilkan dan sehat', 'score' => 2],
            ],
        ],
        [
            'wizard_step' => 16,
            'question_key' => 'q18',
            'section' => 'Warisan',
            'text' => 'Apakah akan mendapatkan Warisan Finansial',
            'note' => "Warisan yang diberikan baik dari Orang tua, atau keluarga lainnya.\nWarisan aset yang dianggap adalah warisan yang sudah menjadi milik anda (bukan yang dijanjikan)",
            'is_scored' => true,
            'sort_order' => 18,
            'options' => [
                'none' => ['label' => 'Tidak ada', 'score' => 0],
                'debt' => ['label' => 'Warisan Hutang', 'score' => -1],
                'asset' => ['label' => 'Warisan Aset', 'score' => 1],
            ],
        ],
    ],
];
