<?php

/**
 * YFD AI Taxonomy v1.0 FINAL REVISED (Juli 2026) — closed list.
 * AI hanya boleh memilih dari daftar ini; bucket ditentukan sistem.
 *
 * @see docs/YFD_AI_Taxonomy_PALING FINAL_REVISED.pdf
 */
return [
    'expense_categories' => [
        'Makanan & Minuman',
        'Tempat Tinggal',
        'Transportasi',
        'Komunikasi',
        'Kesehatan & Kebersihan Diri',
        'Pendidikan',
        'Investasi & Tabungan',
        'Proteksi',
        'Lifestyle & Hiburan',
        'Traveling',
        'Sosial & Keluarga',
        'Bisnis & Karir',
        'Hadiah',
        'Cicilan & Hutang',
        'Pakaian & Aksesoris',
        'Lain-lain',
    ],

    'income_categories' => [
        'Gaji',
        'Bonus',
        'Freelance',
        'Affiliate',
        'Dividen',
        'Bunga Investasi',
        'Cashback',
        'Refund',
        'Penjualan',
        'Sewa Masuk',
        'Transfer Masuk',
        'Lain-lain',
    ],

    'fallback_category' => 'Lain-lain',

    /**
     * Alias lama / AI variants → kategori resmi.
     *
     * @var array<string, string>
     */
    'aliases' => [
        'gaji' => 'Gaji',
        'bonus' => 'Bonus',
        'freelance' => 'Freelance',
        'honor' => 'Freelance',
        'affiliate' => 'Affiliate',
        'afiliasi' => 'Affiliate',
        'komisi' => 'Affiliate',
        'commission' => 'Affiliate',
        'referral' => 'Affiliate',
        'dividen' => 'Dividen',
        'dividend' => 'Dividen',
        'bunga investasi' => 'Bunga Investasi',
        'bunga' => 'Bunga Investasi',
        'cashback' => 'Cashback',
        'refund' => 'Refund',
        'penjualan' => 'Penjualan',
        'sewa masuk' => 'Sewa Masuk',
        'transfer masuk' => 'Transfer Masuk',
        'makan' => 'Makanan & Minuman',
        'makanan' => 'Makanan & Minuman',
        'makanan & minuman' => 'Makanan & Minuman',
        'makanan dan minuman' => 'Makanan & Minuman',
        'jajan' => 'Makanan & Minuman',
        'minuman' => 'Makanan & Minuman',
        'transport' => 'Transportasi',
        'transportasi' => 'Transportasi',
        'listrik' => 'Tempat Tinggal',
        'air' => 'Tempat Tinggal',
        'sewa/tempat tinggal' => 'Tempat Tinggal',
        'sewa' => 'Tempat Tinggal',
        'tempat tinggal' => 'Tempat Tinggal',
        'komunikasi' => 'Komunikasi',
        'kesehatan' => 'Kesehatan & Kebersihan Diri',
        'kesehatan & kebersihan diri' => 'Kesehatan & Kebersihan Diri',
        'laundry' => 'Kesehatan & Kebersihan Diri',
        'cuci baju' => 'Kesehatan & Kebersihan Diri',
        'dry clean' => 'Kesehatan & Kebersihan Diri',
        // Perawatan & kecantikan tetap di kategori Kesehatan (bucket Flexible via Wants).
        'skincare' => 'Kesehatan & Kebersihan Diri',
        'serum' => 'Kesehatan & Kebersihan Diri',
        'make up' => 'Kesehatan & Kebersihan Diri',
        'makeup' => 'Kesehatan & Kebersihan Diri',
        'parfum' => 'Kesehatan & Kebersihan Diri',
        'pendidikan' => 'Pendidikan',
        'saham' => 'Investasi & Tabungan',
        'reksadana' => 'Investasi & Tabungan',
        'emas' => 'Investasi & Tabungan',
        'obligasi' => 'Investasi & Tabungan',
        'tabungan/investasi' => 'Investasi & Tabungan',
        'investasi' => 'Investasi & Tabungan',
        'investasi & tabungan' => 'Investasi & Tabungan',
        'asuransi' => 'Proteksi',
        'proteksi' => 'Proteksi',
        'hiburan' => 'Lifestyle & Hiburan',
        'lifestyle' => 'Lifestyle & Hiburan',
        'lifestyle & hiburan' => 'Lifestyle & Hiburan',
        'subscription' => 'Lifestyle & Hiburan',
        'elektronik' => 'Lifestyle & Hiburan',
        'peralatan' => 'Lifestyle & Hiburan',
        'traveling' => 'Traveling',
        'liburan' => 'Traveling',
        'social' => 'Sosial & Keluarga',
        'sosial' => 'Sosial & Keluarga',
        'sosial & keluarga' => 'Sosial & Keluarga',
        'bisnis' => 'Bisnis & Karir',
        'bisnis & karir' => 'Bisnis & Karir',
        'jasa' => 'Bisnis & Karir',
        'hadiah' => 'Hadiah',
        'cicilan' => 'Cicilan & Hutang',
        'cicilan & hutang' => 'Cicilan & Hutang',
        'pakaian' => 'Pakaian & Aksesoris',
        'pakaian & aksesoris' => 'Pakaian & Aksesoris',
        'pakaian dan aksesoris' => 'Pakaian & Aksesoris',
        'fashion' => 'Pakaian & Aksesoris',
        'baju' => 'Pakaian & Aksesoris',
        'sepatu' => 'Pakaian & Aksesoris',
        'tas' => 'Pakaian & Aksesoris',
        'aksesoris' => 'Pakaian & Aksesoris',
        'seragam' => 'Pakaian & Aksesoris',
        'pajak' => 'Lain-lain',
        'lainnya' => 'Lain-lain',
        'lain-lain' => 'Lain-lain',
        'lain lain' => 'Lain-lain',
    ],

    'source_of_truth_note' => [
        'Taxonomy tertutup (YFD AI Taxonomy FINAL REVISED): AI HANYA memilih dari 16 kategori resmi (+ kategori pemasukan).',
        'AI tidak boleh membuat kategori baru. Jika ragu → Lain-lain.',
        'Layer 1 = Kategori (closed list). Layer 2 = Bucket (otomatis dari mapping sistem).',
        'AI tidak menentukan bucket. Bucket dihitung dari sub-konteks + Need/Wants.',
        'Gym/olahraga berbayar → Lifestyle & Hiburan / Flexible + Social / Wants (bukan Essential).',
        'Laundry/cuci baju → Kesehatan & Kebersihan Diri / Essential Living.',
        'Skincare premium / make-up → Kesehatan & Kebersihan Diri / Flexible + Social (Wants).',
        'Fashion/baju/sepatu → Pakaian & Aksesoris (bukan Lifestyle).',
        'Pengembangan diri → Pendidikan / Future Building (Need atau Wants, bucket sama).',
        'DP rumah/properti → Saving/Investment / Future Building. Cicilan produktif / KPR investasi → Future Building.',
        'Donasi/sedekah/zakat/hadiah → Sosial & Keluarga atau Hadiah / Flexible + Social.',
        'Jenis transaksi dan bucket berbeda: biaya bisnis tetap Pengeluaran, bucket Future Building.',
    ],
];
