<?php

namespace Database\Seeders;

use App\Models\CpDigitalProduct;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DigitalProductSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $products = [
            [
                'code'           => 'yfd-bot-telegram',
                'name'           => 'YFD First Aid',
                'tagline'        => 'Bukan sekedar pencatat keuangan. Ini adalah langkah pertama untuk memahami dan membangun kesehatan finansial Anda.',
                'description'    => "Asisten kesehatan finansial berbasis AI.\n\nCatat transaksi cukup lewat chat/kirim foto struk pembelian. AI akan mengubahnya menjadi Financial Health Dashboard, mendeteksi perilaku impulsif, dan membantu Anda memahami kondisi kesehatan finansial.\n\nPembelian mencakup akses bot & dashboard plus biaya admin selama 1 tahun. Setelah itu, lanjutkan dengan biaya admin Rp10.000/bulan atau Rp99.000/tahun.",
                'icon'           => 'send',
                'badge'          => 'Coming Soon',
                'is_active'      => true,
                'is_featured'    => true,
                'sort'           => 1,
                'price'          => 299000,
                'discount_price' => 199000,
                'currency'       => 'IDR',
                'period'         => '1 tahun (termasuk biaya admin)',
                'features'       => [
                    'Catat transaksi cukup lewat chat',
                    'AI otomatis mengelompokkan pengeluaran/pemasukan',
                    'Dashboard langsung ter-update',
                    'Deteksi pembelian impulsif',
                    'Kenali pola kebiasaan finansial — ketahui bukan hanya ke mana uang Anda pergi, tetapi juga mengapa',
                    'Dapatkan insight & rekomendasi',
                    'Gratis biaya admin selama 1 tahun pertama',
                    'Tahun berikutnya: Rp10.000/bulan atau Rp99.000/tahun',
                ],
                'billing_mode'   => 'soon',
                'cta_label'      => 'Coming Soon',
                'meta_title'     => 'YFD First Aid — Catat Keuangan via Chat',
                'meta_description' => 'Catat keuangan harian via chat di Telegram. Termasuk biaya admin 1 tahun; setelah itu perpanjang Rp10.000/bulan atau Rp99.000/tahun.',
            ],
            [
                'code'           => 'yfd-bot-admin-monthly',
                'name'           => 'Biaya Admin First Aid — Bulanan',
                'tagline'        => 'Perpanjang akses bot & dashboard — Rp10.000/bulan.',
                'description'    => 'Biaya admin bulanan untuk mempertahankan akses YFD First Aid (bot Telegram + dashboard) setelah tahun pertama. Perpanjang 1 bulan setiap pembayaran.',
                'icon'           => 'calendar_month',
                'badge'          => 'Perpanjang',
                'is_active'      => true,
                'is_featured'    => false,
                'sort'           => 2,
                'price'          => 10000,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => 'per bulan',
                'features'       => [
                    'Perpanjang akses bot & dashboard 1 bulan',
                    'Untuk pengguna First Aid setelah tahun pertama',
                    'Bisa diganti ke paket tahunan kapan saja',
                ],
                'billing_mode'   => 'pivot',
                'cta_label'      => 'Bayar Bulanan',
                'meta_title'     => 'Biaya Admin First Aid Bulanan — YFD',
                'meta_description' => 'Perpanjang YFD First Aid dengan biaya admin Rp10.000/bulan.',
            ],
            [
                'code'           => 'yfd-bot-admin-yearly',
                'name'           => 'Biaya Admin First Aid — Tahunan',
                'tagline'        => 'Perpanjang akses bot & dashboard — Rp99.000/tahun.',
                'description'    => 'Biaya admin tahunan untuk mempertahankan akses YFD First Aid (bot Telegram + dashboard) setelah tahun pertama. Lebih hemat dibanding bayar bulanan.',
                'icon'           => 'event_available',
                'badge'          => 'Perpanjang',
                'is_active'      => true,
                'is_featured'    => false,
                'sort'           => 3,
                'price'          => 99000,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => 'per tahun',
                'features'       => [
                    'Perpanjang akses bot & dashboard 12 bulan',
                    'Lebih hemat dibanding Rp10.000 × 12',
                    'Untuk pengguna First Aid setelah tahun pertama',
                ],
                'billing_mode'   => 'pivot',
                'cta_label'      => 'Bayar Tahunan',
                'meta_title'     => 'Biaya Admin First Aid Tahunan — YFD',
                'meta_description' => 'Perpanjang YFD First Aid dengan biaya admin Rp99.000/tahun.',
            ],
            [
                'code'           => 'yfd-ftsa-premium',
                'name'           => 'FTSA',
                'tagline'        => 'Kenali Archetype Keuangan Anda Sebelum Mengatur Uang',
                'description'    => "Dua orang bisa memiliki penghasilan yang sama, tetapi mengambil keputusan finansial yang sangat berbeda. Mengapa?\n\nKarena setiap orang memiliki archetype atau pola kepribadian finansial yang terbentuk dari pengalaman hidup, cara berpikir, dan regulasi diri. FTSA (Financial Trauma Self Assessment) membantu Anda mengenali pola tersebut sehingga Anda dapat memahami mengapa Anda mengambil keputusan finansial tertentu—bukan hanya apa yang harus dilakukan.",
                'icon'           => 'psychology',
                'badge'          => 'Tersedia',
                'is_active'      => true,
                'is_featured'    => true,
                'sort'           => 5,
                'price'          => 50000,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => '12 bulan evaluasi',
                'features'       => [
                    'Hasil Financial Personality Archetype',
                    'Pemetaan kecenderungan regulasi diri finansial',
                    'Skor pada setiap dimensi FTSA',
                    'Penjelasan pola perilaku yang paling dominan',
                    'Area yang berpotensi menghambat Financial Health',
                    'Rekomendasi langkah awal yang sesuai dengan hasil Anda',
                ],
                'billing_mode'   => 'pivot',
                'cta_label'      => 'Unlock FTSA',
                'meta_title'     => 'FTSA — Financial Trauma Self Assessment | YFD',
                'meta_description' => 'Kenali archetype keuangan dan pola perilaku finansial Anda dengan FTSA 1–32. Pahami mengapa Anda mengambil keputusan finansial tertentu.',
            ],
            [
                'code'           => 'yfd-first-aid-ftsa',
                'name'           => 'First Aid + FTSA Bundle',
                'tagline'        => 'Bundling YFD First Aid dan FTSA dalam satu paket.',
                'description'    => "Satu pembelian untuk akses YFD First Aid (bot + dashboard) dan FTSA Premium.\n\nCocok untuk paket lengkap: catat transaksi harian sekaligus kenali archetype keuangan Anda.",
                'icon'           => 'package_2',
                'badge'          => 'Bundle',
                'is_active'      => true,
                'is_featured'    => true,
                'sort'           => 4,
                'price'          => 249000,
                'discount_price' => 229000,
                'currency'       => 'IDR',
                'period'         => '1 tahun First Aid + 12 bulan evaluasi FTSA',
                'features'       => [
                    'Semua fitur YFD First Aid',
                    'Semua fitur FTSA Premium',
                    'Satu lisensi untuk kedua akses',
                    'Cocok untuk onboarding lengkap',
                ],
                'billing_mode'   => 'pivot',
                'cta_label'      => 'Beli Bundle',
                'meta_title'     => 'First Aid + FTSA Bundle | YFD',
                'meta_description' => 'Bundling YFD First Aid dan FTSA dalam satu paket pembelian.',
            ],
            [
                'code'           => 'yfd-ftsa-workshop',
                'name'           => 'FTSA Workshop / Korporat',
                'tagline'        => 'Akses FTSA khusus workshop & kerjasama korporat (tanpa checkout publik).',
                'description'    => "Produk akses FTSA untuk peserta workshop atau mitra korporat.\n\nTidak untuk dijual di checkout publik — diberikan admin lewat menu Tambah User Gratis.",
                'icon'           => 'groups',
                'badge'          => 'Workshop',
                'is_active'      => true,
                'is_featured'    => false,
                'sort'           => 6,
                'price'          => 0,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => '12 bulan evaluasi',
                'features'       => [
                    'Akses FTSA penuh',
                    'Untuk peserta workshop / mitra korporat',
                    'Diberikan admin tanpa pembayaran',
                ],
                'billing_mode'   => 'soon',
                'cta_label'      => 'Via Admin',
                'meta_title'     => 'FTSA Workshop | YFD',
                'meta_description' => 'Akses FTSA khusus workshop dan kerjasama korporat.',
            ],
            [
                'code'           => 'yfd-mobile-app',
                'name'           => 'YFD Mobile App',
                'tagline'        => 'Aplikasi Android & iOS — dashboard visual, target tabungan, alert otomatis.',
                'description'    => 'Aplikasi mobile YFD untuk dashboard visual finansial. Cek health score, monitoring goal, set reminder, dan dapat insight personal — semua di telepon Anda.',
                'icon'           => 'phone_iphone',
                'badge'          => 'Coming Soon',
                'is_active'      => true,
                'is_featured'    => false,
                'sort'           => 10,
                'price'          => 0,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => '—',
                'features'       => [
                    'Dashboard visual cashflow & net worth',
                    'Goal tracking & savings target',
                    'Reminder & alert otomatis',
                    'Sync data dari YFD First Aid',
                ],
                'billing_mode'   => 'soon',
                'cta_label'      => 'Notify Saat Launch',
            ],
            [
                'code'           => 'wealthpedia-premium',
                'name'           => 'Wealthpedia Premium',
                'tagline'        => 'Course self-paced, e-book, dan webinar bulanan tentang practical & emotional finance.',
                'description'    => 'Akses penuh ke konten premium Wealthpedia: kelas online berseri, e-book, dan webinar bulanan dengan dokter finansial QWP.',
                'icon'           => 'school',
                'badge'          => 'Coming Soon',
                'is_active'      => true,
                'is_featured'    => false,
                'sort'           => 20,
                'price'          => 0,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => '—',
                'features'       => [
                    'Course self-paced multi-level',
                    'E-book & worksheet finansial',
                    'Webinar bulanan QWP',
                    'Komunitas eksklusif',
                ],
                'billing_mode'   => 'soon',
                'cta_label'      => 'Notify Saat Launch',
            ],
            [
                'code'           => 'calculator-tools',
                'name'           => 'Calculator Tools',
                'tagline'        => 'Kalkulator dana darurat, KPR, pensiun, dan compound interest — gratis untuk semua.',
                'description'    => 'Kumpulan kalkulator finansial gratis untuk perencanaan keuangan harian. Tidak perlu daftar.',
                'icon'           => 'calculate',
                'badge'          => 'Coming Soon',
                'is_active'      => true,
                'is_featured'    => false,
                'sort'           => 30,
                'price'          => 0,
                'discount_price' => null,
                'currency'       => 'IDR',
                'period'         => 'gratis',
                'features'       => [
                    'Dana Darurat',
                    'KPR / Cicilan',
                    'Dana Pensiun',
                    'Compound Interest',
                ],
                'billing_mode'   => 'soon',
                'cta_label'      => 'Notify Saat Launch',
            ],
        ];

        foreach ($products as $row) {
            CpDigitalProduct::updateOrCreate(['code' => $row['code']], $row);
        }
    }
}
